//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PangeaProject.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PangeaRepoDBEntities : DbContext
    {
        public PangeaRepoDBEntities()
            : base("metadata=res://*/PangeaRepoDB.csdl|res://*/PangeaRepoDB.ssdl|res://*/PangeaRepoDB.msl;provider=System.Data.SqlClient;provider connection string=\"data source = PRATHER-LAPTOP\\SQLEXPRESS; initial catalog = PangeaRepoDB; integrated security = True; MultipleActiveResultSets=True;App=EntityFramework\"")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RepoCopy> RepoCopies { get; set; }
    }
}
